### ISSUE TITLE
Safari doesn't have crisp edges for sprites

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#165]
| safari | chrome |
| --- | --- |
| <img width="111" alt="screenshot 2016-09-10 09 29 47" src="https://cloud.githubusercontent.com/assets/2454505/18411990/457684ae-7739-11e6-9d19-b00ffc6b7e95.png"> | <img width="112" alt="screenshot 2016-09-10 09 30 08" src="https://cloud.githubusercontent.com/assets/2454505/18411991/4ee6b2de-7739-11e6-82e4-2853c662f8a1.png"> |

**Comment by ami** [comment]
https://jsfiddle.net/tzv24nay/

^ open in safari - looks like the property doesn't work for background images 😭

[this](https://bugs.webkit.org/show_bug.cgi?id=97991) seems relevent but i have no idea what it means haha

**Comment by ami** [comment]
closing as this works in safari now!
