### ISSUE TITLE
Update robots.txt

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#214]
update it to not include users dexes or profiles

![image](https://cloud.githubusercontent.com/assets/2454505/20870833/646e5a88-ba43-11e6-8779-1900e30aa5d8.png)

**Comment by BTolliday** [comment]
Looks like this bug has been fixed. Can this issue be updated?

**Comment by ami** [comment]
seems like you're right, thanks!
