### ISSUE TITLE
missing pokemon

### ISSUE THREAD

**Issue by Droidem** [pokedextracker/pokedextracker.com#222]
Hey there! 

I love this project and it's ease of use. Is it possible to add a page for the pokedex that spits out all missing pokemon and how they can be obtained?

**Comment by ami** [comment]
great feature request - i'll be closing this issue though as it's already encapsulated [here](https://github.com/pokedextracker/pokedextracker.com/issues/136) and [here](https://github.com/pokedextracker/pokedextracker.com/issues/197). thanks again!

**Comment by Droidem** [comment]
fml. thanks! sorry I didn't look hard enough.

**Comment by ami** [comment]
no problem at all! we're also admittedly not very organized/descriptive with our issues haha
