### ISSUE TITLE
Add CLA for contributors 

### ISSUE THREAD

**Issue by ashcoding** [pokedextracker/pokedextracker.com#232]
Just want to make a suggestion to have a CLA for contributors to https://github.com/pokedextracker/pokedextracker.com and https://github.com/pokedextracker/api.pokedextracker.com. 

Might not be needed as I don't think there are lots of people contributing PRs, but might be nice to have.

**Comment by ami** [comment]
hey @ashcoding - thanks for the suggestion! at this point, we think a CLA will be overkill, since we don't have that many contributors. we may re-evaluate this in the future, though!
