### ISSUE TITLE
Using gen 7 pokedex removes location info for gen 6

### ISSUE THREAD

**Issue by SimenB** [pokedextracker/pokedextracker.com#249]
It would be awesome to be able to view all the info at once. ATM I won't be able to add my gen 7 stuff because I'm not yet done with gen 6 games (or I'll have to keep switching back and forth...)

Right now the code just checks `if (generation === 6) {`. Maybe a new option should be added for tracking gen 6 and 7 simultaneously?

**Comment by AussieEevee** [comment]
Perhaps instead of specifying Generation 6 or 7, remove that option and have the site include all 6 games by default.
