### ISSUE TITLE
Add a lock mode

### ISSUE THREAD

**Issue by AussieEevee** [pokedextracker/pokedextracker.com#263]
Right now, if you click a Pokemon, instead of selecting it, it marks it as caught. I'd like to see a lock icon in the corner whre I can lock it which would cause clicking it to select the Pokemon for viewing instead, and I'd have to unlock it to make changes.

**Comment by ami** [comment]
thanks for the suggestion, @AussieEevee! our current preferred UX is to keep the tracker as easy to edit as possible, and to use the (i) icon to show pokemon information.
