### ISSUE TITLE
Event Pokemon tracking

### ISSUE THREAD

**Issue by MonkeyJamboree** [pokedextracker/pokedextracker.com#300]
So, I'm liking the site so far, though I currently can't use it due to lack of ability to track different forms/genders (another issue was already started for this, however)...

But one thing I noticed is there's no real way to track Event Pokemon. Some of us collectors like to track what ones we have and collect them as well. There are many different "versions" of events as well, and tracking it yourself on a spreadsheet can be a bit time-consuming. Perhaps add this as another type of "Dex" that can be tracked by using info from Serebii and Bulbapedia and PokemonDB?

**Comment by ami** [comment]
event pokemon are encompassed in #256
