### ISSUE TITLE
Add latest Pokemon from Ultra Sun / Ultra Moon

### ISSUE THREAD

**Issue by nalexander50** [pokedextracker/pokedextracker.com#310]
Since the release of Ultra Sun and Ultra Moon nearly a year ago, new Pokemon were added to the Pokedex. We will also see the introduction of Meltan later this Fall with Pokemon Let's GO. The website should be updated to reflect the new Pokemon.

- Poipole
- Naganadel
- Stakataka
- Blacephalon
- Zeraora
- Meltan

**Comment by ami** [comment]
hey @nalexander50,

thanks for reaching out! we actually already support all the pokemon from us+um - you just have to either create a new dex or edit your existing dex and choose "Ultra Sun" or "Ultra Moon":

![image](https://user-images.githubusercontent.com/5498072/46187534-e48c0800-c298-11e8-9301-f32cde329300.png)

as far as meltan, we'll definitely be adding support for let's go eevee + pikachu, and will include meltan then. i'll be creating a separate issue for that when the time comes.

thanks again for the comment!
