### ISSUE TITLE
add newly-available non-galarian forms to SwSh national dex

### ISSUE THREAD

**Issue by myrrien** [pokedextracker/pokedextracker.com#355]
With the release of Pokemon HOME new non-galarian forms are transferable to the game, namely

A-raichu
A-vulpix
A-ninetales
A-diglett
A-dugtrio
A-meowth
A-persian
ponyta
rapidash
weezing
corsola
zigzagoon
linoone
darumaka
darmanitan
stunfisk

**Comment by ami** [comment]
thank you! we will definitely do this.
