### ISSUE TITLE
Buizel entry for Ultra Sun and Ultra Moon Error

### ISSUE THREAD

**Issue by BrynnMountain** [pokedextracker/pokedextracker.com#356]
The Buizel info on the right for Ultra Sun and Ultra Moon says "Breed Buizel", when it should read "Breed Floatzel" as Floatzel is catchable in the Ultra Wormholes, but Buizel is only breedable from that Floatzel.

**Comment by ami** [comment]
thanks for letting us know! we'll get that fixed. we get our catch info directly from [serebii](https://www.serebii.net/pokedex-sm/418.shtml) so looks like it's originally a bug from there!

**Comment by robinjoseph08** [comment]
we've updated the location info! thanks again for the help!
