### ISSUE TITLE
Add view options for filtering pokémon

### ISSUE THREAD

**Issue by adrianodennanni** [pokedextracker/pokedextracker.com#360]
While using pokedextracker for completing my Pokémon Home, I felt this needed a component that allows you to show only captured or non captured pokémon. This component could also toggle box numeration on/off.
It could also have an option to show all pokémon in a list style, not in cards style.
Also, it could have a "print" function with the selected view.

Also, I'm offering my help to develop this features.

**Comment by McInkay** [comment]
#359 is a PR already up for the first part of this.

**Comment by adrianodennanni** [comment]
In this case, I'm closing the issue and will reopen it once the first part is merged.
