### ISSUE TITLE
Show all forms

### ISSUE THREAD

**Issue by AussieEevee** [pokedextracker/pokedextracker.com#363]
I have a Sword pokedex. I'm using it as my Home pokedex... and I'm trying to create a living dex with one of every form for a pokemon. I'd like to see other forms displayed independently of the pokemon... or at least the option to do that.

Thanks.

**Comment by myrrien** [comment]
I think it mostly depends on what you consider a form? like, unown male/female indeedee? and if you go for m/f differences, do you consider only great differences like the above or even small differences like pikachu?

**Comment by AussieEevee** [comment]
> I think it mostly depends on what you consider a form?

I was thinking of normal, Alolan, Galarian, and shiny forms. Though it would be nice to show all the unown forms, but I was thinking mostly about regional and shiny forms.

**Comment by myrrien** [comment]
alolan and galarian are already tracked in their own box at the bottom, for shinies you make another dex

**Comment by AussieEevee** [comment]
I didn't know about them at the bottom. Would be nice if there was an option to mix those forms in with the main forms.

**Comment by myrrien** [comment]
there has been a poll with the two options and this is what the community has decided

**Comment by ami** [comment]
Thanks for the request @AussieEevee! In the future we hope to support all types of forms (genders, unown, etc), but these would have to be added as options for those who do want to toggle them on. I'm going to close this issue as it's encapsulated here: #256
