### ISSUE TITLE
Living Dex Icons are Mixed Up

### ISSUE THREAD

**Issue by superllama1** [pokedextracker/pokedextracker.com#385]
I have a full (all pokemon and forms) living dex saved on the site. Since a recent update within the last few days, I've noticed that the names of the Pokemon I have selected as caught are indeed valid, but now the icons for each Pokemon are not for the correct Pokemon. 

Example: Charmeleon now shows the icon for Mega Charizard.

**Comment by superllama1** [comment]
The tags for my dex are "National" and "Shield"

**Comment by superllama1** [comment]
![image](https://user-images.githubusercontent.com/7789386/86019173-e3e35100-b9eb-11ea-97fe-91973f1b76fe.png)

**Comment by ami** [comment]
@superllama1 thanks for reaching out! could you try hard refreshing your browser to clear your cache, or try in incognito mode? we just launched a new spritesheet in preparation for the isle of armor update.

**Comment by superllama1** [comment]
Yup! That fixed it. Thanks!
