### ISSUE TITLE
Pokemon Images incorrect

### ISSUE THREAD

**Issue by thewizard99** [pokedextracker/pokedextracker.com#386]
The pokedex images are all out of whack. Missing Venasaurs and every pokemon is moved by one on the image, so Venasaur is coming up as Charmander.

**Comment by ami** [comment]
@thewizard99 thanks for reaching out! could you try hard refreshing your browser to clear your cache, or try in incognito mode? we just launched a new spritesheet in preparation for the isle of armor update.
