### ISSUE TITLE
Add Melmetal as a gigantamax form

### ISSUE THREAD

**Issue by devonwasson** [pokedextracker/pokedextracker.com#394]
Melmetal's Gigantamax form is now obtainable. It is obtained by connecting Pokemon Go to Pokemon Home, transferring a pokemon from Go to Home, opening Pokemon Home on a mobile device, and collecting the resulting mystery gift. This Melmetal can be transferred to Sword and Shield and used in those games.

**Comment by ami** [comment]
fixed https://github.com/pokedextracker/pokedextracker.com/pull/398
