### ISSUE TITLE
Update catch information for Magikarp in LGPE

### ISSUE THREAD

**Issue by jakethegamingwolf** [pokedextracker/pokedextracker.com#403]
So I was on Route 6 in Let's Go Eevee and catching pokemon and went to the water pool when a magikarp appeared. I checked to see what routes magikarp can spawn on and Route 6 was not listed as a place it can spawn at.

**Comment by Azekthi** [comment]
I've got the official guide book and it shows that Magikarp can spawn at Routes 4, 6, 10~13, and 18~25, as well as the Seafoam Islands and Cerulean Cave, so pokedextracker is missing routes 6 and 11.
