### ISSUE TITLE
Ash Ketchum’s livingdex is missing Pokémon.

### ISSUE THREAD

**Issue by Logan-will-not-use-this** [pokedextracker/pokedextracker.com#416]
Falsities in the living dex of Ash Ketchum:
In rotation:
Gigantamax Pikachu not selected.
Dragonite not selected.
Gengar not selected.
Lucario not selected.
Sirfetche’d not selected.
Dracovish not selected.
Traveling with:
N/A
With Professor Oak:
N/A
With Kukui and Burnet:
Incineroar not selected.
Melmetal not seected.
At the Cerise Laboratory:
Mr. Mime not selected.
In training:
N/A
Released; Officially owned:
Naganadel not selected.
Released; Temporarily owned:
Seaking not selected.
Buzzwole not selected.
Stakataka not selected.
Pheromosa not selected.
Released; Traded away:
N/A
Released; Given away:
N/A
Traveled with:
Haunter not selected.
Larvitar not selected.
Solgaleo not selected.

**Comment by ami** [comment]
closing, we've updated this but also it's not super important for us to keep this up to date.
