### ISSUE TITLE
Tracking for Legends Arceus

### ISSUE THREAD

**Issue by Fleker** [pokedextracker/pokedextracker.com#432]
Hey folks, I've started using this site for tracking my Pokemon in Home and BDSP and wanted to share my thoughts on how tracking should work for PLA.

I would like to be able to break out the tasks for each Pokemon individually so I can put in the exact number that I currently have and have the website be able to calculate the current research level. There are probably several degrees of completion that should be tracked: research level 10 and perfect. I think these are two separate goals that people may want to achieve, and even then may want to focus on one or the other.

It may also be useful to track simply which ones have been caught in general so I as the player know where to start: my pasture or the world.

I haven't seen any other discussions on PLA yet, so I just wanted to open this to give some suggestions and discuss other ideas. Thanks!

**Comment by fmartingr** [comment]
I would start by adding the pokemon list so we can track a living dex, then a manual check when that entry is complete (research = 10) and another one for perfection.

After that we could think of integrating complex stuff like automatic calculation of completion which entirely depends on the game's data mining (or manual creation) of all the poemons tasks, levels and bonuses. 

For me it would be more than enough to have a the first iteration (I'm only achieving completion, not perfection) which would also be way simpler both to develop and to use IMO: updating the pokemon list is a pain enough as it is, now imagine going one by one checking tasks manually when you already have like 150+ captured.

**Comment by ami** [comment]
thank you for the suggestions! we'll likely be rolling this out in a phase approch. i'll be closing this ticket to create our own that we will use to track progress.
