### ISSUE TITLE
Legends: Arceus Support

### ISSUE THREAD

**Issue by ami** [pokedextracker/pokedextracker.com#437]
- [x] db updates
  - [x] game/game family
  - [x] pokemon
  - [x] evolutions
  - [x] dex type
  - [x] locations
- [ ] sprites
  - [x] add to spritesheet
  - [ ] edit frontend to use the correct one

**Comment by mmarquez76** [comment]
hi there! are there any of these tasks you'd be willing to delegate out? I've got some free time over the long weekend and would love to contribute.

**Comment by robinjoseph08** [comment]
Hey @mmarquez76, thanks for the offer! We're actually just about done with all of the changes (just doing some last few touchups with the sprites), and then we'll be ready to go! We just didn't keep the checklist up to date 😅  Hoping to get it released soon!
