### ISSUE TITLE
Suggestion: Alt forms

### ISSUE THREAD

**Issue by RealCornQueen** [pokedextracker/pokedextracker.com#449]
Add alternate forms for, Vivlion, Deerling/Sawsbuck, Unown etc

and ability to toggle shiny locked pokemon, and disable gmax forms

**Comment by Azekthi** [comment]
Forms handling: #256 

Shiny lock: #277

**Comment by HL971** [comment]
Scarlet/Violet Has 3 forms of Tauros, the tracker only has one

**Comment by ami** [comment]
closing as this is a dupe of the two tickets @Azekthi mentioned above.
