### ISSUE TITLE
Site has become inaccessible

### ISSUE THREAD

**Issue by Azekthi** [pokedextracker/pokedextracker.com#450]
Whenever I try to load a dex page from a new tab, I'm getting an infinite "Loading..." screen. If I try to click on the links on the home page to a sample dex, or go to my profile, I get a MissingNo error.

I cleared my browser storage to try logging in with a fresh session, and I got this error:

> JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by BlaxadowFire** [comment]
I got the same issue.
Also got a `Unexpected token < in JSON at position 0` when trying to log in.

**Comment by BlaxadowFire** [comment]
Seems to be resolved now.
@Azekthi

**Comment by ami** [comment]
There was some momentary downtime due to high traffic which has been resolved.
