### ISSUE TITLE
Feature Request: PLA Living Shiny Dex Without Legendaries

### ISSUE THREAD

**Issue by pcoll9991** [pokedextracker/pokedextracker.com#458]
Just a small thing but it would be amazing to have a Legends Arceus living shiny dex tracker with the option to not have legendary pokemon in it due to them being shiny locked in this game. I love the current one and use it to keep track of mine and this is my only tiny complaint!

**Comment by ami** [comment]
closing, dupe of: https://github.com/pokedextracker/pokedextracker.com/issues/277
