### ISSUE TITLE
Basculin Missing From Hisuian Forms

### ISSUE THREAD

**Issue by JoshMountain** [pokedextracker/pokedextracker.com#467]
White stripe basculin is a Hisuian form and should be listed here.

**Comment by JoshMountain** [comment]
@robinjoseph08 it looks like maybe you were working on this in #465?

**Comment by ami** [comment]
hi all! that fix is actually unrelated.

white stripe basculin is not considered a hisuian form from what we can tell. for example, it is not listed in [this page on serebii](https://www.serebii.net/legendsarceus/hisuianforms.shtml) or [this page](https://game8.co/games/Pokemon-Legends-Arceus/archives/343569) on game8. its name is also not "Hisuian Basculin". therefore, we consider it just another form of basculin (along with red stripe and blue stripe) that happens to only be available in hisui, and so we do not include it in the hisuian form section. in the future if we support tracking forms other than regional forms (e.g. red stripe and blue stripe basculin, west sea and east sea shellos, etc), then this support would be added along with. 

closing this issue accordingly!
