### ISSUE TITLE
Feature request: Add non-changeable alt forms and gender differences

### ISSUE THREAD

**Issue by StrawDeath** [pokedextracker/pokedextracker.com#479]
Currently trying to track my shiny living dex, but at the moment the only alternate forms pokedextracker.com tracks are G-max and regional variants. This means that I can't track, for example, the fact that I've got both Toxtricity forms shiny. Naturally, this isn't just the case with shinies, but also all alternate forms. 

It makes sense that different forms of some Pokémon like Castform or Deoxys aren't tracked, as it is possible to change between them freely by various means. But it would make sense to separately track forms that can't be switched between, such as Urshifu, Lycanrock, or anything with a gender difference.

I'm sorry in advance if there's something I'm doing wrong with this post, as I literally only created a Github account to suggest this, so I don't really know how the site works.

**Comment by ami** [comment]
You're totally fine! Thanks for the feedback. Merging into the main issue we have for this feature request: https://github.com/pokedextracker/pokedextracker.com/issues/256
