### ISSUE TITLE
National Dex ID's are out

### ISSUE THREAD

**Issue by tombomb** [pokedextracker/pokedextracker.com#481]
not sure if you want to touch this now or still wait for Home to get the update, but I just got an email from pokemon about there pokedex on there website being updated to show the new ones, and there there with national dex ID's. format of the site is kinda crap but if you just keep scrolling and loading more you can get to the new ones

https://www.pokemon.com/us/pokedex

<img width="938" alt="image" src="https://user-images.githubusercontent.com/544509/212492725-1646db2e-745d-4db7-a5f6-dfb9f795baab.png">

**Comment by Fleker** [comment]
Home update has been confirmed for May 24th.

**Comment by tombomb** [comment]
The update is now out

**Comment by ami** [comment]
merging into #490
