### ISSUE TITLE
Feature Request: Returning and New Pokemon (DLC Tracker)

### ISSUE THREAD

**Issue by vlastarnost** [pokedextracker/pokedextracker.com#487]
Can we have a separate tracker for returning and new Pokemon exclusively found on DLC? I noticed for SwSh Regional Dex, it also lists  duplicates already found on the base game. I understand that there's the National Dex, but it would be far easier to complete a Living Dex if we are presented with a DLC only list.

With the upcoming DLC for SV, I hope this feature will be added, so does an update for SwSh.

**Comment by ami** [comment]
Thank you for the feedback! We decided on the current structure for Expansion Passes based on [a poll we conducted](https://twitter.com/PokedexTracker/status/1275293224702103552) on our Twitter. We will follow the same format for future Expansion Passes/DLC. We may add the option to toggle this in the future if there is enough feedback, but for now it will stay the same.
