### ISSUE TITLE
Feature Request: Scarlet/Violet tracker should include all Tauros forms

### ISSUE THREAD

**Issue by Fleker** [pokedextracker/pokedextracker.com#488]
The Pokedex for Scarlet/Violet includes an entry for Paldean Tauros.

![image](https://user-images.githubusercontent.com/3291635/224761873-7cd587a3-2cb9-4d37-bd15-376f3b584034.png)

However, Tauros has three distinct "breeds" within its Paldean form which should be represented.

![image](https://user-images.githubusercontent.com/3291635/224762017-cf7ae9c7-820f-485a-b40e-1ac9546ee047.png)

**Comment by ami** [comment]
Merging into https://github.com/pokedextracker/pokedextracker.com/issues/256 as this is a generic request to support alternative forms.
