### ISSUE TITLE
Feature Request: Scarlet/Violet tracker should include all Vivillon forms

### ISSUE THREAD

**Issue by Fleker** [pokedextracker/pokedextracker.com#489]
Vivillon is a Pokemon who, when it evolves from Spewpa, can become one of many different forms. However, this only appears once in the tracker.

![image](https://user-images.githubusercontent.com/3291635/224762405-d5466db2-ac85-4c92-b4f4-f3db43492735.png)

Particularly in the case of shiny hunting, where it's now possible to get [the majority of shiny Vivillon forms](https://twitter.com/JoeMerrick/status/1634104139553685505) in SV since v1.2, it is very difficult to track which ones you've gotten so far.

I haven't started shiny hunting these yet, but when I do it will be a tough process to remember which ones I've got and which I need. Pokedex Tracker should in theory support this, as the alternative option will be some kind of alternative tracker.

![image](https://user-images.githubusercontent.com/3291635/224762933-0c6100b6-b871-40b1-86ea-4349a97d8244.png)

**Comment by ami** [comment]
Merging into https://github.com/pokedextracker/pokedextracker.com/issues/256 as this is a generic request to support alternative forms.
