### ISSUE TITLE
Unable to Login or Register

### ISSUE THREAD

**Issue by blancogerardo94** [pokedextracker/pokedextracker.com#509]
Getting ready for DLC and encountered this issue. 🙃 

https://github.com/pokedextracker/pokedextracker.com/assets/18353720/67158656-364e-4858-8cd6-0da043747810

**Comment by ami** [comment]
Hi @blancogerardo94, I'm unable to reproduce this issue, and we're not getting reports from other users. Can you try resetting the cache and cookies on your browser, or trying in incognito mode?

Thanks!

**Comment by blancogerardo94** [comment]
Cleared cache and tried incognito with no luck. Able to log in on safari
