### ISSUE TITLE
Add Blueberry POKÉDEX TRACKER

### ISSUE THREAD

**Issue by Orionsilver** [pokedextracker/pokedextracker.com#528]
please Add Blueberry POKÉDEX TRACKER into your beautiful website please

**Comment by fleeting** [comment]
If you haven't seen, indigo disk dex has been added: https://pokedextracker.com/blog/the-indigo-disk-scarlet-violet-expansion-pass-full-support/

**Comment by ami** [comment]
https://github.com/pokedextracker/pokedextracker.com/pull/529
