### ISSUE TITLE
Mobile Chrome incognito on iOS can't login

### ISSUE THREAD

**Issue by robinjoseph08** [pokedextracker/pokedextracker.com#90]
`QuotaExceededError: DOM Exception 22`

this shouldn't be happening since incognito should allow all session storage but just wipe it at the end, but for some reason, it's not allowing it at all

**Comment by codeurge** [comment]
This issue can be closed as it's no longer a problem with the React refactor. Great job on that, by the way.

**Comment by ami** [comment]
thanks @codeurge!! unfortunately the problem still exists - the issue was originally for mobile chrome incognito on iOS. i've updated the issue title to reflect that!
